// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzmokjwzkjnsntebscee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6bW9rand6a2puc250ZWJzY2VlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMTgxNzIsImV4cCI6MjA1OTg5NDE3Mn0.jCNFcz9o0yChEB768KwDx6cn8kPjk5Ja1N-Cq3iJSNQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);